Should fix remaining test issues

diff --git a/bin/dokku-daemon b/bin/dokku-daemon
--- a/bin/dokku-daemon
+++ b/bin/dokku-daemon
@@ -30,7 +30,8 @@ json_encode() {
   fi
 
   # Replace newlines and double quotes with their escaped counterparts
-  local output=$(echo -n "$1" | sed ':a;N;$!ba;s/\n/\\n/g' | sed 's/"/\\"/g')
+  local output
+  output=$(echo -n "$1" | sed ':a;N;$!ba;s/\n/\\n/g' | sed 's/"/\\"/g')
 
   printf '{"ok":%s,"output":"%s"}' "$status" "$output"
 }
@@ -49,7 +50,7 @@ cleanup() {
 }
 
 server() {
-  trap 'cleanup' TERM ABRT QUIT EXIT KILL
+  trap 'cleanup' TERM ABRT QUIT EXIT
 
   # remove previously created devices
   rm -f "$DOKKU_LOCK_PATH"
@@ -81,7 +82,8 @@ remove_flags() {
 
 
 is_valid_command() {
-  local cmd="$(remove_flags "$@" | tr ' ' "\n")"
+  local cmd
+  cmd="$(remove_flags "$@" | tr ' ' "\n")"
   local valid=false
   grep -q "^${cmd[0]}$" "$DOKKU_LOCK_PATH" && valid=true
   [[ "${cmd[0]}" == *help ]] && valid=true
@@ -89,10 +91,12 @@ is_valid_command() {
 }
 
 connection() {
-  while read -u 3 input; do
+  while read -u 3 -r input; do
     # parse command components into an array
+    # shellcheck disable=SC2206
     local cmd=($input)
-    local is_valid=$(is_valid_command "${cmd[@]}")
+    local is_valid
+    is_valid=$(is_valid_command "${cmd[@]}")
 
     case "${cmd[0]}" in
       enter|shell)
@@ -111,7 +115,7 @@ connection() {
       *)
         if [[ "$is_valid" == "true" ]]; then
           set +e
-          if [[ " ${cmd[@]} " == *" apps:destroy "* ]] && [[ ! " ${cmd[@]} " == *" --force "* ]]; then
+          if [[ " ${cmd[*]} " == *" apps:destroy "* ]] && [[ ! " ${cmd[*]} " == *" --force "* ]]; then
             response="Requires --force flag"
             status=1
           else
@@ -152,7 +156,7 @@ main() {
         exit 0
         ;;
       *)
-        echo "Error: Unkown option $1" 1>&2
+        echo "Error: Unknown option $1" 1>&2
         exit 1
         ;;
     esac
